# Generated by Django 3.2.3 on 2021-05-30 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('face_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('job', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=20)),
                ('woreda', models.CharField(max_length=20)),
                ('kebele', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_image/')),
                ('mother_name', models.CharField(max_length=200)),
                ('emergnency_case', models.CharField(max_length=200)),
                ('emergnency_number', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
